---
- hosts: ipa.otus.lan
  become: true
  vars_files:
    - defaults/main.yml
  roles:
    - common
    - server
  
- hosts: client1.otus.lan, client2.otus.lan
  become: true
  vars_files:
    - defaults/main.yml
  roles:
    - common
    - client
...